server:
  port: 8080
  servlet:
    context-path: /tech

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/techdb"
    username: root
    password: Admin@123
  jpa:
    show-sql: true

jwt:
  signerKey: "JT1u3UntCMv2FeJDKiAfNLwJYmujvLb+/GMYR69NYNhYZpJkGNTPAyNSk7tlJyRL"